# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrimo
email: team@andrimo.com
description: >
  All About Android
logo: "https://m.andrimo.com/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m.andrimo.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
permalink: /:title/

name: 'Team Andrimo'
bio: >
  Author of Andrimo, A Offical Publisher of Andrimo. Publish Article on Weekly Basis
author_image: "https://www.gravatar.com/avatar/f5114248b51ae98a7bbe5ef430c5a164?s=250&d=mm&r=x"
twitter_username: andrimoblog
# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
